name: Update Last Updated Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        run: |
          git fetch --depth=2
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "CHANGED_FILES=$(cat changed_files.txt)" >> $GITHUB_ENV

      - name: Update Markdown files
        run: |
          while IFS= read -r file; do
            if [[ $file == *.md ]]; then
              LAST_UPDATED=$(git log -1 --format="%cd" --date=short -- "$file")
              sed -i "s/^Last updated: .*/Last updated: $LAST_UPDATED/" "$file"
            fi
          done < changed_files.txt

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add $(cat changed_files.txt)
          git commit -m "Update last updated date"
          git push
