name: Update Last Updated Date

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32

      - name: Update Markdown files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            if [[ $file == *.md ]]; then
              LAST_UPDATED=$(git log -1 --format="%cd" --date=short -- $file)
              sed -i "s/^Last updated: .*/Last updated: $LAST_UPDATED/" $file
            fi
          done

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ steps.changed-files.outputs.modified_files }}
          git commit -m "Update last updated date"
          git push
